<a href="https://colab.research.google.com/github/shohruhinomjonov691-hub/kervan/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [4]:
import numpy as np

arr = np.array([1, 3, 5, 7])
print('numpy_array:', arr)
arr.shape

numpy_array: [1 3 5 7]


(4,)

In [5]:
arr2 = np.array([[1, 3, 5, 7], [4, 6, 8, 9]])
print('numpy_array:', arr2)
arr2.shape

numpy_array: [[1 3 5 7]
 [4 6 8 9]]


(2, 4)

In [19]:
# dtype()
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [20]:
# reshape()
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print('shaped_array:', b)

shaped_array: [[1 2 3]
 [4 5 6]]


In [21]:
# astype()
a = np.array([1, 2, 3])
b = a.astype(float)
print('float:', b)

float: [1. 2. 3.]


In [14]:
# np.zeros(), np.ones() => dummy data
z = np.zeros((2, 3))
o = np.ones((2, 3))

print('zeros:', z)
print('ones:', o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# ndim
a = np.array([[1, 2], [3, 4] ])
print('ndim:', a.ndim)


ndim: 2


In [22]:
# arange()
a = np.arange(1, 7)
print('arange:', a)

arange: [1 2 3 4 5 6]


In [23]:
# sum(), mean(), max(), min()

a = np.array([1, 2, 3, 4])

print('sum:', a.sum())
print('mean:', a.mean())
print('max:', a.max())
print('min:', a.min())

sum: 10
mean: 2.5
max: 4
min: 1


In [25]:
# flatten()

a = np.array([[1, 2], [3, 4] ])
print('flatten:', a.flatten())

flatten: [1 2 3 4]


In [26]:
# T (Transpose)
a = np.array([[1, 2], [3, 4] ])
print('transpose:', a.T)

transpose: [[1 3]
 [2 4]]


In [29]:
# dot() @
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print('dot/multiplication:', a.dot(b))

dot/multiplication: [[ 4  4]
 [10  8]]


In [30]:
# random.rand()
a = np.random.rand(2, 3) # => 0.0 and 1.0 / 0.0 included / 1.0 excluded
print('random rand:', a)

random rand: [[0.38328249 0.19780864 0.47618725]
 [0.45780804 0.02497996 0.19923523]]
